---
title: "Playground"
author: "Andrew"
date: "11/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(sf)
library(mapview)
library(rgdal)

```

```{r}
wrs <- st_read('Data/In/Landsat/wrs2_cleaned_datetime.shp') %>% filter(MODE == 'D')

```

```{r sample variables}
start <- Sys.Date() %>% as.numeric()
stop <- start + 30
date <- "2020-11-03"
input <- data.frame("timezone" = "GMT")

x <-
  paste0(date, l7.lookup[l7.lookup$Path == path, ]$first) %>% as.POSIXct(tz = input$timezone) %>% strftime(format = "%H:%M:%S",
                                                                                                           tz = input$timezone,
                                                                                                           usetz = TRUE) %>% as.character.Date()
y <-
  paste0(date, l7.lookup[l7.lookup$Path == path, ]$last) %>% as.POSIXct(tz = input$timezone)

passing_period <- interval(x, y, input$timezone)

```

```{r function, echo=FALSE}
generate <- function(lon, lat, ref) {
    df <- returnPR(lon, lat)
    start <- input$dates[1] %>% as.numeric()
    stop <- input$dates[2] %>% as.numeric()
    
    #Update the map
    map(lon, lat) %>%  addPolygons(
      data = df$shape.geometry,
      color = 'blue',
      weight = 2,
      label = paste0('Path: ', df$path, '; Row: ', df$row),
      highlightOptions = highlightOptions(
        color = 'white',
        weight = 3,
        bringToFront = TRUE
      )
    )
    
    #Create range of dates from start - end
    range <- start:stop %>% as.Date('1970-01-01') %>% as.character()
    start_date_cycle <-
      start - (ref$Cycle_Start[1] %>% as.Date() %>% as.numeric()) %% 16 + 1
    
    #Lookup table where every date in range has corresponding cycle
    table <-
      cbind("Date" = range,
            "Cycle" = getCycles(1, 16, length(range), start_date_cycle - 1)) %>% as.data.frame()
    
    updating_table <- data.frame()
    
    for (r in 1:length(df$path)) {
      cycle <- ref[ref$Path == df$path[r],]$Cycle
      dates <- table[table$Cycle == cycle,]$Date %>% as.character()
      
      if (is_empty(dates))
        next
      
      path <- df$path[r]
      row <- df$row[r]
      
      updating_table <-
        rbind(
          updating_table,
          cbind(
            "Date" = dates,
            "Time" = NA,
            "Path" = df$path[r],
            "Row" = df$row[r],
            "MGRS" = NA,
            "Lat" = round(lat, 5),
            "Lon" = round(lon, 5),
            "Satellite" = (ref$Satellite[[1]] %>% as.character())
          )
        )
    }
    update_output(updating_table)
  }
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
