---
title: "Landsat_Aquisition_Times"
author: "Simon Topp"
date: "10/9/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(RCurl)
library(tidyverse)
library(lubridate)
library(sf)

knitr::opts_chunk$set(echo = TRUE)
```


## Download a full cycle of landsat overpasses
```{r}
dates <- seq(ymd(Sys.Date()) - 16, ymd(Sys.Date()), 'days')

timePull <- function(date, sat){
  month <- month(date, label = T)
  year <- year(date)
  date <- format(date, format = "%b-%d-%Y")
  
  url <- paste0('https://landsat.usgs.gov/landsat/all_in_one_pending_acquisition/',sat,'/Pend_Acq/y',year,'/',month,'/',date,'.txt')
  
read_fwf(url, fwf_widths(c(5,5,20,NA)), col_types = c('ii??')) %>%
  filter(!is.na(X1)) %>%
  select(Path = X1, Row = X2, Img.Start = X3) %>%
  mutate(time.parsed = parse_date_time(Img.Start,'j-HMS'))
}

l8.times <- map2_dfr(dates, 'L8',timePull)
l7.times <- map2_dfr(dates, 'L7', timePull)
```

## Acquire reference times for each path/row
```{r}
wrs <- st_read('Data/In/Landsat/wrs2_cleaned.shp')
wrs <- wrs[wrs$MODE == 'D',]

times <- data.frame("PATH" = wrs$PATH, "ROW" = wrs$ROW)


mergeTime <- function(into, sat, MAXCOUNT) {
  
  into <- cbind(into, data.frame("Time" = NA))

  for (i in 0:MAXCOUNT-1) {
    ref <- timePull(Sys.Date() - i, sat)
    ref$time.parsed <-
      ref$time.parsed %>% strftime(format = "%H:%M:%S",
                                   tz = "GMT",
                                   usetz = TRUE)
    
    names(ref)[names(ref) == "time.parsed"] <- "Time"
    
    into <-
      left_join(into, ref, by = c('PATH' = 'Path', 'ROW' = 'Row')) %>%
      mutate(Time = coalesce(Time.x, Time.y)) %>% select(-Time.x,-Time.y,-Img.Start)
    
    if (!anyNA(into$Time)) {
      break
    }
  }
  
  colname <- paste0(sat, "_Time")
  
  #Rename the column of acquisition times "L8_Times" or "L7_Times" and add column "Times" to be NA so function can be repeated
  names(into)[names(into) == "Time"] <- colname
  return(into)

}

times <- mergeTime(times, "L8", 80)
times <- mergeTime(times, "L7", 80)

joined <- left_join(wrs, times)
joined <- joined %>% unique()

st_write(joined, "Data/In/wrs2_cleaned_datetime.shp")
```

## Acquire reference times for all paths, 1-233. Some return periods have holes
```{r}
acquire <- function(sat) {

  df <- data.frame("Satellite" = sat, Path = 1:233, first = NA, last= NA)
  
  date <- Sys.Date() + 1
  
  # Acquires datetimes from today going backward until all Paths have a reference
  max_count = 0
  
  while(anyNA(df) && max_count < 50) {
    
    ref <- timePull(date, sat)
    ref$time.parsed <- ref$time.parsed %>% strftime(format = "%H:%M:%S", tz = "GMT", usetz = TRUE)
    
    for (path in ref$Path %>% unique()) {
      
      # Only add to paths without a reference
      if(anyNA(df[path,]) ) {
          first <- ref %>% filter(Path == path)  %>% {.[[1,4]]} %>% as_datetime() %>% format("%H:%M:%S")
          last <- ref %>% filter(Path == path) %>% last() %>% last() %>% as_datetime() %>% format("%H:%M:%S")
          df[path,]$first <- first
          df[path,]$last <- last
      }
    }
    date = date - 1
    max_count = max_count + 1
  }
  return(df)
}


l7.lookup <- merge(read_csv('Data/In/Landsat/landsat7_lookup.csv'), acquire("L7"))
l8.lookup <- merge(read_csv('Data/In/Landsat/landsat8_lookup.csv'), acquire("L8"))

```


```{r}

```
## Look at times spatially and see if they make sense

```{r}
wrs <- st_read('data/in/Landsat/wrs2_asc_desc.shp') %>% filter(MODE == 'D')

l7.sf <- l7.times %>%
  mutate(hour = hour(time.parsed)) %>%
  left_join(wrs, by = c('Path' = 'PATH', 'Row'= 'ROW')) %>%
  st_as_sf() %>%
  st_centroid()

mapview::mapview(l7.sf, zcol = 'hour')


l8.sf <- l8.times %>%
  mutate(hour = hour(time.parsed)) %>%
  left_join(wrs, by = c('Path' = 'PATH', 'Row'= 'ROW')) %>%
  st_as_sf() %>%
  st_centroid()

mapview::mapview(l8.sf, zcol = 'hour')
```
